name: Release Mobile Android Logging
on:
  push:
    branches: [ main ]

jobs:
  bump_version:
    env:
      JDK_VERSION: 17
    permissions:
      id-token: write
      contents: write
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Run deployment workflow
        uses: govuk-one-login/mobile-android-pipelines@217b8fb9b8f5f1e763e8d56427d68180d422d62b
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
