name: Release Mobile Android Logging
on:
  push:
    branches: [ main ]

jobs:
  bump_version:
    env:
      JDK_VERSION: 17
      GITHUB_ACTOR: ${{ secrets.MODULE_FETCH_TOKEN_USERNAME}}
      GITHUB_TOKEN: ${{ secrets.MODULE_FETCH_TOKEN }}
    permissions:
      id-token: write
      contents: write
      packages: write
    runs-on: ubuntu-22.04

    steps:
      - name: Run deployment workflow
        uses: govuk-one-login/mobile-android-pipelines@71f28a7f97f9d8dfabffd791bc9a00fc32c17324
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
