name: Release Mobile Android Logging
on:
  push:
    branches: [ main ]

jobs:
  bump_version:
    env:
      JDK_VERSION: 17
    permissions:
      id-token: write
      contents: write
      packages: write
    runs-on: ubuntu-22.04

    steps:
      - name: Run deployment workflow
        uses: govuk-one-login/mobile-android-pipelines@4bae5f390135e3f7d60fcd646376b198de8c467e
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
